"""Add magic link token model

Revision ID: d164a9272269
Revises: c4c9ad304714
Create Date: 2025-09-30 13:08:10.522872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd164a9272269'
down_revision: Union[str, None] = 'c4c9ad304714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magic_link_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_link_tokens_expires_at'), 'magic_link_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_magic_link_tokens_phone'), 'magic_link_tokens', ['phone'], unique=False)
    op.create_index(op.f('ix_magic_link_tokens_token'), 'magic_link_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_magic_link_tokens_token'), table_name='magic_link_tokens')
    op.drop_index(op.f('ix_magic_link_tokens_phone'), table_name='magic_link_tokens')
    op.drop_index(op.f('ix_magic_link_tokens_expires_at'), table_name='magic_link_tokens')
    op.drop_table('magic_link_tokens')
    # ### end Alembic commands ###
